name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    env:
      coi: 0.1.7
      util: 0.12.1
      ffmpeg: 0.12.10
      core: 0.12.6

    steps:
      - uses: actions/checkout@v4

      - run: mkdir _site

      - id: cache
        uses: actions/cache@v3
        with:
          path: deps
          key: cache-${{env.coi}}-${{env.util}}-${{env.ffmpeg}}-${{env.core}}

      - name: deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir deps
          cd deps
          curl -sS -o coi-serviceworker.min.js \
            "https://unpkg.com/coi-serviceworker@${coi}/coi-serviceworker.min.js"
          curl -sS -o ffmpeg-util.js \
            "https://unpkg.com/@ffmpeg/util@${util}/dist/umd/index.js"
          curl -sS \
            "https://unpkg.com/@ffmpeg/ffmpeg@${ffmpeg}/dist/umd/ffmpeg.js" \
            "https://unpkg.com/@ffmpeg/ffmpeg@${ffmpeg}/dist/umd/ffmpeg.js.map" \
            "https://unpkg.com/@ffmpeg/ffmpeg@${ffmpeg}/dist/umd/814.ffmpeg.js" \
            "https://unpkg.com/@ffmpeg/ffmpeg@${ffmpeg}/dist/umd/814.ffmpeg.js.map" \
            "https://unpkg.com/@ffmpeg/core@${core}/dist/umd/ffmpeg-core.js" \
            "https://unpkg.com/@ffmpeg/core@${core}/dist/umd/ffmpeg-core.wasm"

      - run: |
          cp index.html extsub.js extsub.css coi-config.js mp4txt.py spinner.svg _site
          cp deps/* _site

      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
      - uses: actions/deploy-pages@v2
        id: deployment
